server:
    logLevel: RTCSTATS_LOG_LEVEL
    appEnvironment: RTCSTATS_ENVIRONMENT
    keyPath: RTCSTATS_KEYPATH
    certPath: RTCSTATS_CERTPath
    tempPath: RTCSTATS_TEMPPATH
    useHTTPS: RTCSTATS_HTTPS
    skipLoadBalancerIp: RTCSTATS_SKIP_LOAD_BALANCER_IP
    jsonConsoleLog: RTCSTATS_JSON_CONSOLE_LOG

localstack:
    endpoint: LOCALSTACK_ENDPOINT
    
amplitude:
    key: RTCSTATS_AMPLITUDE_KEY

firehose:
    region: RTCSTATS_FIREHOSE_AWS_REGION
    meetingStatsStream: RTCSTATS_FIREHOSE_MEETING_STREAM
    pcStatsStream: RTCSTATS_FIREHOSE_PC_STREAM
    trackStatsStream: RTCSTATS_FIREHOSE_TRACKS_STREAM
    e2ePingStream: RTCSTATS_FIREHOSE_E2E_PING_STREAM
    faceLandmarksStream: RTCSTATS_FIREHOSE_FACE_LANDMARKS_STREAM
    meetingEventStream: RTCSTATS_FIREHOSE_MEETING_EVENT_STREAM

s3:
    accessKeyId: RTCSTATS_S3_ACCESSKEYID
    secretAccessKey: RTCSTATS_S3_SECRETACCESSKEY
    region: RTCSTATS_S3_AWS_REGION
    bucket: RTCSTATS_S3_BUCKET
    useIAMAuth: RTCSTATS_S3_USEIAMAUTH
    signedLinkExpirationSec: RTCSTATS_S3_SIGNEDLINKEXPIRATIONSEC

dynamo:
    tableName: RTCSTATS_METADATA_TABLE

webhooks:
    apiEndpoint: RTCSTATS_WEBHOOK_ENDPOINT
    jwtAudience: RTCSTATS_JWT_AUDIENCE
    jwtIssuer: RTCSTATS_JWT_ISSUER

secretmanager:
    region: RTCSTATS_AWS_SECRET_REGION
    jwtSecretId: RTCSTATS_JWT_SECRET_ID